// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audit_usess.proto

package sp;

public final class AuditUsess {
  private AuditUsess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface T_USER_SESSIONOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes sessionid = 1;
    /**
     * <code>required bytes sessionid = 1;</code>
     *
     * <pre>
     * 会话标识ID，主键
     * </pre>
     */
    boolean hasSessionid();
    /**
     * <code>required bytes sessionid = 1;</code>
     *
     * <pre>
     * 会话标识ID，主键
     * </pre>
     */
    com.google.protobuf.ByteString getSessionid();

    // required bytes sip = 2;
    /**
     * <code>required bytes sip = 2;</code>
     *
     * <pre>
     * 源IP
     * </pre>
     */
    boolean hasSip();
    /**
     * <code>required bytes sip = 2;</code>
     *
     * <pre>
     * 源IP
     * </pre>
     */
    com.google.protobuf.ByteString getSip();

    // optional int32 userid = 3;
    /**
     * <code>optional int32 userid = 3;</code>
     *
     * <pre>
     * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
     * </pre>
     */
    boolean hasUserid();
    /**
     * <code>optional int32 userid = 3;</code>
     *
     * <pre>
     * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
     * </pre>
     */
    int getUserid();

    // required bytes logname = 4;
    /**
     * <code>required bytes logname = 4;</code>
     *
     * <pre>
     * 主帐号
     * </pre>
     */
    boolean hasLogname();
    /**
     * <code>required bytes logname = 4;</code>
     *
     * <pre>
     * 主帐号
     * </pre>
     */
    com.google.protobuf.ByteString getLogname();

    // optional bytes uname = 5;
    /**
     * <code>optional bytes uname = 5;</code>
     *
     * <pre>
     * 用户姓名
     * </pre>
     */
    boolean hasUname();
    /**
     * <code>optional bytes uname = 5;</code>
     *
     * <pre>
     * 用户姓名
     * </pre>
     */
    com.google.protobuf.ByteString getUname();

    // optional int32 ouid = 6;
    /**
     * <code>optional int32 ouid = 6;</code>
     *
     * <pre>
     * 组织机构ID
     * </pre>
     */
    boolean hasOuid();
    /**
     * <code>optional int32 ouid = 6;</code>
     *
     * <pre>
     * 组织机构ID
     * </pre>
     */
    int getOuid();

    // optional bytes ouname = 7;
    /**
     * <code>optional bytes ouname = 7;</code>
     *
     * <pre>
     * 组织机构名称
     * </pre>
     */
    boolean hasOuname();
    /**
     * <code>optional bytes ouname = 7;</code>
     *
     * <pre>
     * 组织机构名称
     * </pre>
     */
    com.google.protobuf.ByteString getOuname();

    // optional bytes region_code = 8;
    /**
     * <code>optional bytes region_code = 8;</code>
     *
     * <pre>
     * 主帐号地域编码
     * </pre>
     */
    boolean hasRegionCode();
    /**
     * <code>optional bytes region_code = 8;</code>
     *
     * <pre>
     * 主帐号地域编码
     * </pre>
     */
    com.google.protobuf.ByteString getRegionCode();

    // optional bytes region_name = 9;
    /**
     * <code>optional bytes region_name = 9;</code>
     *
     * <pre>
     * 主帐号地域名称
     * </pre>
     */
    boolean hasRegionName();
    /**
     * <code>optional bytes region_name = 9;</code>
     *
     * <pre>
     * 主帐号地域名称
     * </pre>
     */
    com.google.protobuf.ByteString getRegionName();

    // optional int32 employeetype_id = 10;
    /**
     * <code>optional int32 employeetype_id = 10;</code>
     *
     * <pre>
     * 主帐号类型ID
     * </pre>
     */
    boolean hasEmployeetypeId();
    /**
     * <code>optional int32 employeetype_id = 10;</code>
     *
     * <pre>
     * 主帐号类型ID
     * </pre>
     */
    int getEmployeetypeId();

    // optional bytes employeetype = 11;
    /**
     * <code>optional bytes employeetype = 11;</code>
     *
     * <pre>
     * 主帐号类型名称
     * </pre>
     */
    boolean hasEmployeetype();
    /**
     * <code>optional bytes employeetype = 11;</code>
     *
     * <pre>
     * 主帐号类型名称
     * </pre>
     */
    com.google.protobuf.ByteString getEmployeetype();

    // optional int32 employeestation_id = 12;
    /**
     * <code>optional int32 employeestation_id = 12;</code>
     *
     * <pre>
     * 主帐号岗位ID
     * </pre>
     */
    boolean hasEmployeestationId();
    /**
     * <code>optional int32 employeestation_id = 12;</code>
     *
     * <pre>
     * 主帐号岗位ID
     * </pre>
     */
    int getEmployeestationId();

    // optional bytes employeestation = 13;
    /**
     * <code>optional bytes employeestation = 13;</code>
     *
     * <pre>
     * 主帐号岗位名称
     * </pre>
     */
    boolean hasEmployeestation();
    /**
     * <code>optional bytes employeestation = 13;</code>
     *
     * <pre>
     * 主帐号岗位名称
     * </pre>
     */
    com.google.protobuf.ByteString getEmployeestation();

    // required int64 oper_sec = 14;
    /**
     * <code>required int64 oper_sec = 14;</code>
     *
     * <pre>
     * 操作时间，秒
     * </pre>
     */
    boolean hasOperSec();
    /**
     * <code>required int64 oper_sec = 14;</code>
     *
     * <pre>
     * 操作时间，秒
     * </pre>
     */
    long getOperSec();

    // optional int64 oper_msec = 15;
    /**
     * <code>optional int64 oper_msec = 15;</code>
     *
     * <pre>
     * 操作时间，毫秒
     * </pre>
     */
    boolean hasOperMsec();
    /**
     * <code>optional int64 oper_msec = 15;</code>
     *
     * <pre>
     * 操作时间，毫秒
     * </pre>
     */
    long getOperMsec();

    // optional bytes workinfo = 16;
    /**
     * <code>optional bytes workinfo = 16;</code>
     *
     * <pre>
     * 工单信息
     * </pre>
     */
    boolean hasWorkinfo();
    /**
     * <code>optional bytes workinfo = 16;</code>
     *
     * <pre>
     * 工单信息
     * </pre>
     */
    com.google.protobuf.ByteString getWorkinfo();

    // optional bytes logreason = 17;
    /**
     * <code>optional bytes logreason = 17;</code>
     *
     * <pre>
     * 登录事由
     * </pre>
     */
    boolean hasLogreason();
    /**
     * <code>optional bytes logreason = 17;</code>
     *
     * <pre>
     * 登录事由
     * </pre>
     */
    com.google.protobuf.ByteString getLogreason();

    // required .sp.LOG_TYPE log_type = 18;
    /**
     * <code>required .sp.LOG_TYPE log_type = 18;</code>
     *
     * <pre>
     * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
     * </pre>
     */
    boolean hasLogType();
    /**
     * <code>required .sp.LOG_TYPE log_type = 18;</code>
     *
     * <pre>
     * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
     * </pre>
     */
    AuditEnum.LOG_TYPE getLogType();

    // optional int32 reserved0 = 19;
    /**
     * <code>optional int32 reserved0 = 19;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasReserved0();
    /**
     * <code>optional int32 reserved0 = 19;</code>
     *
     * <pre>
     * </pre>
     */
    int getReserved0();

    // optional int32 reserved1 = 20;
    /**
     * <code>optional int32 reserved1 = 20;</code>
     */
    boolean hasReserved1();
    /**
     * <code>optional int32 reserved1 = 20;</code>
     */
    int getReserved1();

    // optional bytes reserved2 = 21;
    /**
     * <code>optional bytes reserved2 = 21;</code>
     */
    boolean hasReserved2();
    /**
     * <code>optional bytes reserved2 = 21;</code>
     */
    com.google.protobuf.ByteString getReserved2();

    // optional bytes reserved3 = 22;
    /**
     * <code>optional bytes reserved3 = 22;</code>
     */
    boolean hasReserved3();
    /**
     * <code>optional bytes reserved3 = 22;</code>
     */
    com.google.protobuf.ByteString getReserved3();

    // optional bytes reserved4 = 23;
    /**
     * <code>optional bytes reserved4 = 23;</code>
     */
    boolean hasReserved4();
    /**
     * <code>optional bytes reserved4 = 23;</code>
     */
    com.google.protobuf.ByteString getReserved4();
  }
  /**
   * Protobuf type {@code sp.T_USER_SESSION}
   */
  public static final class T_USER_SESSION extends
      com.google.protobuf.GeneratedMessage
      implements T_USER_SESSIONOrBuilder {
    // Use T_USER_SESSION.newBuilder() to construct.
    private T_USER_SESSION(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private T_USER_SESSION(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final T_USER_SESSION defaultInstance;
    public static T_USER_SESSION getDefaultInstance() {
      return defaultInstance;
    }

    public T_USER_SESSION getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private T_USER_SESSION(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sessionid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sip_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userid_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              logname_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              uname_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ouid_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              ouname_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              regionCode_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              regionName_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              employeetypeId_ = input.readInt32();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              employeetype_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              employeestationId_ = input.readInt32();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              employeestation_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              operSec_ = input.readInt64();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              operMsec_ = input.readInt64();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              workinfo_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              logreason_ = input.readBytes();
              break;
            }
            case 144: {
              int rawValue = input.readEnum();
              AuditEnum.LOG_TYPE value = AuditEnum.LOG_TYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(18, rawValue);
              } else {
                bitField0_ |= 0x00020000;
                logType_ = value;
              }
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              reserved0_ = input.readInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00080000;
              reserved1_ = input.readInt32();
              break;
            }
            case 170: {
              bitField0_ |= 0x00100000;
              reserved2_ = input.readBytes();
              break;
            }
            case 178: {
              bitField0_ |= 0x00200000;
              reserved3_ = input.readBytes();
              break;
            }
            case 186: {
              bitField0_ |= 0x00400000;
              reserved4_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AuditUsess.internal_static_sp_T_USER_SESSION_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AuditUsess.internal_static_sp_T_USER_SESSION_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              T_USER_SESSION.class, Builder.class);
    }

    public static com.google.protobuf.Parser<T_USER_SESSION> PARSER =
        new com.google.protobuf.AbstractParser<T_USER_SESSION>() {
      public T_USER_SESSION parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new T_USER_SESSION(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<T_USER_SESSION> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes sessionid = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString sessionid_;
    /**
     * <code>required bytes sessionid = 1;</code>
     *
     * <pre>
     * 会话标识ID，主键
     * </pre>
     */
    public boolean hasSessionid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes sessionid = 1;</code>
     *
     * <pre>
     * 会话标识ID，主键
     * </pre>
     */
    public com.google.protobuf.ByteString getSessionid() {
      return sessionid_;
    }

    // required bytes sip = 2;
    public static final int SIP_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sip_;
    /**
     * <code>required bytes sip = 2;</code>
     *
     * <pre>
     * 源IP
     * </pre>
     */
    public boolean hasSip() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes sip = 2;</code>
     *
     * <pre>
     * 源IP
     * </pre>
     */
    public com.google.protobuf.ByteString getSip() {
      return sip_;
    }

    // optional int32 userid = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private int userid_;
    /**
     * <code>optional int32 userid = 3;</code>
     *
     * <pre>
     * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
     * </pre>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 userid = 3;</code>
     *
     * <pre>
     * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
     * </pre>
     */
    public int getUserid() {
      return userid_;
    }

    // required bytes logname = 4;
    public static final int LOGNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString logname_;
    /**
     * <code>required bytes logname = 4;</code>
     *
     * <pre>
     * 主帐号
     * </pre>
     */
    public boolean hasLogname() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes logname = 4;</code>
     *
     * <pre>
     * 主帐号
     * </pre>
     */
    public com.google.protobuf.ByteString getLogname() {
      return logname_;
    }

    // optional bytes uname = 5;
    public static final int UNAME_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString uname_;
    /**
     * <code>optional bytes uname = 5;</code>
     *
     * <pre>
     * 用户姓名
     * </pre>
     */
    public boolean hasUname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes uname = 5;</code>
     *
     * <pre>
     * 用户姓名
     * </pre>
     */
    public com.google.protobuf.ByteString getUname() {
      return uname_;
    }

    // optional int32 ouid = 6;
    public static final int OUID_FIELD_NUMBER = 6;
    private int ouid_;
    /**
     * <code>optional int32 ouid = 6;</code>
     *
     * <pre>
     * 组织机构ID
     * </pre>
     */
    public boolean hasOuid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 ouid = 6;</code>
     *
     * <pre>
     * 组织机构ID
     * </pre>
     */
    public int getOuid() {
      return ouid_;
    }

    // optional bytes ouname = 7;
    public static final int OUNAME_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString ouname_;
    /**
     * <code>optional bytes ouname = 7;</code>
     *
     * <pre>
     * 组织机构名称
     * </pre>
     */
    public boolean hasOuname() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes ouname = 7;</code>
     *
     * <pre>
     * 组织机构名称
     * </pre>
     */
    public com.google.protobuf.ByteString getOuname() {
      return ouname_;
    }

    // optional bytes region_code = 8;
    public static final int REGION_CODE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString regionCode_;
    /**
     * <code>optional bytes region_code = 8;</code>
     *
     * <pre>
     * 主帐号地域编码
     * </pre>
     */
    public boolean hasRegionCode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes region_code = 8;</code>
     *
     * <pre>
     * 主帐号地域编码
     * </pre>
     */
    public com.google.protobuf.ByteString getRegionCode() {
      return regionCode_;
    }

    // optional bytes region_name = 9;
    public static final int REGION_NAME_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString regionName_;
    /**
     * <code>optional bytes region_name = 9;</code>
     *
     * <pre>
     * 主帐号地域名称
     * </pre>
     */
    public boolean hasRegionName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes region_name = 9;</code>
     *
     * <pre>
     * 主帐号地域名称
     * </pre>
     */
    public com.google.protobuf.ByteString getRegionName() {
      return regionName_;
    }

    // optional int32 employeetype_id = 10;
    public static final int EMPLOYEETYPE_ID_FIELD_NUMBER = 10;
    private int employeetypeId_;
    /**
     * <code>optional int32 employeetype_id = 10;</code>
     *
     * <pre>
     * 主帐号类型ID
     * </pre>
     */
    public boolean hasEmployeetypeId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 employeetype_id = 10;</code>
     *
     * <pre>
     * 主帐号类型ID
     * </pre>
     */
    public int getEmployeetypeId() {
      return employeetypeId_;
    }

    // optional bytes employeetype = 11;
    public static final int EMPLOYEETYPE_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString employeetype_;
    /**
     * <code>optional bytes employeetype = 11;</code>
     *
     * <pre>
     * 主帐号类型名称
     * </pre>
     */
    public boolean hasEmployeetype() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional bytes employeetype = 11;</code>
     *
     * <pre>
     * 主帐号类型名称
     * </pre>
     */
    public com.google.protobuf.ByteString getEmployeetype() {
      return employeetype_;
    }

    // optional int32 employeestation_id = 12;
    public static final int EMPLOYEESTATION_ID_FIELD_NUMBER = 12;
    private int employeestationId_;
    /**
     * <code>optional int32 employeestation_id = 12;</code>
     *
     * <pre>
     * 主帐号岗位ID
     * </pre>
     */
    public boolean hasEmployeestationId() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 employeestation_id = 12;</code>
     *
     * <pre>
     * 主帐号岗位ID
     * </pre>
     */
    public int getEmployeestationId() {
      return employeestationId_;
    }

    // optional bytes employeestation = 13;
    public static final int EMPLOYEESTATION_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString employeestation_;
    /**
     * <code>optional bytes employeestation = 13;</code>
     *
     * <pre>
     * 主帐号岗位名称
     * </pre>
     */
    public boolean hasEmployeestation() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes employeestation = 13;</code>
     *
     * <pre>
     * 主帐号岗位名称
     * </pre>
     */
    public com.google.protobuf.ByteString getEmployeestation() {
      return employeestation_;
    }

    // required int64 oper_sec = 14;
    public static final int OPER_SEC_FIELD_NUMBER = 14;
    private long operSec_;
    /**
     * <code>required int64 oper_sec = 14;</code>
     *
     * <pre>
     * 操作时间，秒
     * </pre>
     */
    public boolean hasOperSec() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int64 oper_sec = 14;</code>
     *
     * <pre>
     * 操作时间，秒
     * </pre>
     */
    public long getOperSec() {
      return operSec_;
    }

    // optional int64 oper_msec = 15;
    public static final int OPER_MSEC_FIELD_NUMBER = 15;
    private long operMsec_;
    /**
     * <code>optional int64 oper_msec = 15;</code>
     *
     * <pre>
     * 操作时间，毫秒
     * </pre>
     */
    public boolean hasOperMsec() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int64 oper_msec = 15;</code>
     *
     * <pre>
     * 操作时间，毫秒
     * </pre>
     */
    public long getOperMsec() {
      return operMsec_;
    }

    // optional bytes workinfo = 16;
    public static final int WORKINFO_FIELD_NUMBER = 16;
    private com.google.protobuf.ByteString workinfo_;
    /**
     * <code>optional bytes workinfo = 16;</code>
     *
     * <pre>
     * 工单信息
     * </pre>
     */
    public boolean hasWorkinfo() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional bytes workinfo = 16;</code>
     *
     * <pre>
     * 工单信息
     * </pre>
     */
    public com.google.protobuf.ByteString getWorkinfo() {
      return workinfo_;
    }

    // optional bytes logreason = 17;
    public static final int LOGREASON_FIELD_NUMBER = 17;
    private com.google.protobuf.ByteString logreason_;
    /**
     * <code>optional bytes logreason = 17;</code>
     *
     * <pre>
     * 登录事由
     * </pre>
     */
    public boolean hasLogreason() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional bytes logreason = 17;</code>
     *
     * <pre>
     * 登录事由
     * </pre>
     */
    public com.google.protobuf.ByteString getLogreason() {
      return logreason_;
    }

    // required .sp.LOG_TYPE log_type = 18;
    public static final int LOG_TYPE_FIELD_NUMBER = 18;
    private AuditEnum.LOG_TYPE logType_;
    /**
     * <code>required .sp.LOG_TYPE log_type = 18;</code>
     *
     * <pre>
     * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
     * </pre>
     */
    public boolean hasLogType() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>required .sp.LOG_TYPE log_type = 18;</code>
     *
     * <pre>
     * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
     * </pre>
     */
    public AuditEnum.LOG_TYPE getLogType() {
      return logType_;
    }

    // optional int32 reserved0 = 19;
    public static final int RESERVED0_FIELD_NUMBER = 19;
    private int reserved0_;
    /**
     * <code>optional int32 reserved0 = 19;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasReserved0() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional int32 reserved0 = 19;</code>
     *
     * <pre>
     * </pre>
     */
    public int getReserved0() {
      return reserved0_;
    }

    // optional int32 reserved1 = 20;
    public static final int RESERVED1_FIELD_NUMBER = 20;
    private int reserved1_;
    /**
     * <code>optional int32 reserved1 = 20;</code>
     */
    public boolean hasReserved1() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional int32 reserved1 = 20;</code>
     */
    public int getReserved1() {
      return reserved1_;
    }

    // optional bytes reserved2 = 21;
    public static final int RESERVED2_FIELD_NUMBER = 21;
    private com.google.protobuf.ByteString reserved2_;
    /**
     * <code>optional bytes reserved2 = 21;</code>
     */
    public boolean hasReserved2() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional bytes reserved2 = 21;</code>
     */
    public com.google.protobuf.ByteString getReserved2() {
      return reserved2_;
    }

    // optional bytes reserved3 = 22;
    public static final int RESERVED3_FIELD_NUMBER = 22;
    private com.google.protobuf.ByteString reserved3_;
    /**
     * <code>optional bytes reserved3 = 22;</code>
     */
    public boolean hasReserved3() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    /**
     * <code>optional bytes reserved3 = 22;</code>
     */
    public com.google.protobuf.ByteString getReserved3() {
      return reserved3_;
    }

    // optional bytes reserved4 = 23;
    public static final int RESERVED4_FIELD_NUMBER = 23;
    private com.google.protobuf.ByteString reserved4_;
    /**
     * <code>optional bytes reserved4 = 23;</code>
     */
    public boolean hasReserved4() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    /**
     * <code>optional bytes reserved4 = 23;</code>
     */
    public com.google.protobuf.ByteString getReserved4() {
      return reserved4_;
    }

    private void initFields() {
      sessionid_ = com.google.protobuf.ByteString.EMPTY;
      sip_ = com.google.protobuf.ByteString.EMPTY;
      userid_ = 0;
      logname_ = com.google.protobuf.ByteString.EMPTY;
      uname_ = com.google.protobuf.ByteString.EMPTY;
      ouid_ = 0;
      ouname_ = com.google.protobuf.ByteString.EMPTY;
      regionCode_ = com.google.protobuf.ByteString.EMPTY;
      regionName_ = com.google.protobuf.ByteString.EMPTY;
      employeetypeId_ = 0;
      employeetype_ = com.google.protobuf.ByteString.EMPTY;
      employeestationId_ = 0;
      employeestation_ = com.google.protobuf.ByteString.EMPTY;
      operSec_ = 0L;
      operMsec_ = 0L;
      workinfo_ = com.google.protobuf.ByteString.EMPTY;
      logreason_ = com.google.protobuf.ByteString.EMPTY;
      logType_ = AuditEnum.LOG_TYPE.LOG_UNKNOWN;
      reserved0_ = 0;
      reserved1_ = 0;
      reserved2_ = com.google.protobuf.ByteString.EMPTY;
      reserved3_ = com.google.protobuf.ByteString.EMPTY;
      reserved4_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSessionid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperSec()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, sessionid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, sip_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, logname_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, uname_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, ouid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, ouname_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, regionCode_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, regionName_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, employeetypeId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, employeetype_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, employeestationId_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, employeestation_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, operSec_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt64(15, operMsec_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, workinfo_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, logreason_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeEnum(18, logType_.getNumber());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(19, reserved0_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeInt32(20, reserved1_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeBytes(21, reserved2_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeBytes(22, reserved3_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeBytes(23, reserved4_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, sessionid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sip_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, logname_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, uname_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ouid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, ouname_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, regionCode_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, regionName_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, employeetypeId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, employeetype_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, employeestationId_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, employeestation_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, operSec_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, operMsec_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, workinfo_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, logreason_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(18, logType_.getNumber());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, reserved0_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, reserved1_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, reserved2_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(22, reserved3_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(23, reserved4_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static T_USER_SESSION parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static T_USER_SESSION parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static T_USER_SESSION parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static T_USER_SESSION parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static T_USER_SESSION parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static T_USER_SESSION parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static T_USER_SESSION parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static T_USER_SESSION parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static T_USER_SESSION parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static T_USER_SESSION parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(T_USER_SESSION prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sp.T_USER_SESSION}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements T_USER_SESSIONOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AuditUsess.internal_static_sp_T_USER_SESSION_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AuditUsess.internal_static_sp_T_USER_SESSION_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                T_USER_SESSION.class, Builder.class);
      }

      // Construct using sp.AuditUsess.T_USER_SESSION.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sessionid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        sip_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        logname_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        uname_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        ouid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        ouname_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        regionCode_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        regionName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        employeetypeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        employeetype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        employeestationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        employeestation_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        operSec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        operMsec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        workinfo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00008000);
        logreason_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00010000);
        logType_ = AuditEnum.LOG_TYPE.LOG_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00020000);
        reserved0_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        reserved1_ = 0;
        bitField0_ = (bitField0_ & ~0x00080000);
        reserved2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00100000);
        reserved3_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00200000);
        reserved4_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00400000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AuditUsess.internal_static_sp_T_USER_SESSION_descriptor;
      }

      public T_USER_SESSION getDefaultInstanceForType() {
        return T_USER_SESSION.getDefaultInstance();
      }

      public T_USER_SESSION build() {
        T_USER_SESSION result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public T_USER_SESSION buildPartial() {
        T_USER_SESSION result = new T_USER_SESSION(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionid_ = sessionid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sip_ = sip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.logname_ = logname_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uname_ = uname_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ouid_ = ouid_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ouname_ = ouname_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.regionCode_ = regionCode_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.regionName_ = regionName_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.employeetypeId_ = employeetypeId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.employeetype_ = employeetype_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.employeestationId_ = employeestationId_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.employeestation_ = employeestation_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.operSec_ = operSec_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.operMsec_ = operMsec_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.workinfo_ = workinfo_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.logreason_ = logreason_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.logType_ = logType_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.reserved0_ = reserved0_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.reserved1_ = reserved1_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.reserved2_ = reserved2_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.reserved3_ = reserved3_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.reserved4_ = reserved4_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof T_USER_SESSION) {
          return mergeFrom((T_USER_SESSION)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(T_USER_SESSION other) {
        if (other == T_USER_SESSION.getDefaultInstance()) return this;
        if (other.hasSessionid()) {
          setSessionid(other.getSessionid());
        }
        if (other.hasSip()) {
          setSip(other.getSip());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasLogname()) {
          setLogname(other.getLogname());
        }
        if (other.hasUname()) {
          setUname(other.getUname());
        }
        if (other.hasOuid()) {
          setOuid(other.getOuid());
        }
        if (other.hasOuname()) {
          setOuname(other.getOuname());
        }
        if (other.hasRegionCode()) {
          setRegionCode(other.getRegionCode());
        }
        if (other.hasRegionName()) {
          setRegionName(other.getRegionName());
        }
        if (other.hasEmployeetypeId()) {
          setEmployeetypeId(other.getEmployeetypeId());
        }
        if (other.hasEmployeetype()) {
          setEmployeetype(other.getEmployeetype());
        }
        if (other.hasEmployeestationId()) {
          setEmployeestationId(other.getEmployeestationId());
        }
        if (other.hasEmployeestation()) {
          setEmployeestation(other.getEmployeestation());
        }
        if (other.hasOperSec()) {
          setOperSec(other.getOperSec());
        }
        if (other.hasOperMsec()) {
          setOperMsec(other.getOperMsec());
        }
        if (other.hasWorkinfo()) {
          setWorkinfo(other.getWorkinfo());
        }
        if (other.hasLogreason()) {
          setLogreason(other.getLogreason());
        }
        if (other.hasLogType()) {
          setLogType(other.getLogType());
        }
        if (other.hasReserved0()) {
          setReserved0(other.getReserved0());
        }
        if (other.hasReserved1()) {
          setReserved1(other.getReserved1());
        }
        if (other.hasReserved2()) {
          setReserved2(other.getReserved2());
        }
        if (other.hasReserved3()) {
          setReserved3(other.getReserved3());
        }
        if (other.hasReserved4()) {
          setReserved4(other.getReserved4());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSessionid()) {

          return false;
        }
        if (!hasSip()) {

          return false;
        }
        if (!hasLogname()) {

          return false;
        }
        if (!hasOperSec()) {

          return false;
        }
        if (!hasLogType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        T_USER_SESSION parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (T_USER_SESSION) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes sessionid = 1;
      private com.google.protobuf.ByteString sessionid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sessionid = 1;</code>
       *
       * <pre>
       * 会话标识ID，主键
       * </pre>
       */
      public boolean hasSessionid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes sessionid = 1;</code>
       *
       * <pre>
       * 会话标识ID，主键
       * </pre>
       */
      public com.google.protobuf.ByteString getSessionid() {
        return sessionid_;
      }
      /**
       * <code>required bytes sessionid = 1;</code>
       *
       * <pre>
       * 会话标识ID，主键
       * </pre>
       */
      public Builder setSessionid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sessionid = 1;</code>
       *
       * <pre>
       * 会话标识ID，主键
       * </pre>
       */
      public Builder clearSessionid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionid_ = getDefaultInstance().getSessionid();
        onChanged();
        return this;
      }

      // required bytes sip = 2;
      private com.google.protobuf.ByteString sip_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sip = 2;</code>
       *
       * <pre>
       * 源IP
       * </pre>
       */
      public boolean hasSip() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes sip = 2;</code>
       *
       * <pre>
       * 源IP
       * </pre>
       */
      public com.google.protobuf.ByteString getSip() {
        return sip_;
      }
      /**
       * <code>required bytes sip = 2;</code>
       *
       * <pre>
       * 源IP
       * </pre>
       */
      public Builder setSip(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sip = 2;</code>
       *
       * <pre>
       * 源IP
       * </pre>
       */
      public Builder clearSip() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sip_ = getDefaultInstance().getSip();
        onChanged();
        return this;
      }

      // optional int32 userid = 3;
      private int userid_ ;
      /**
       * <code>optional int32 userid = 3;</code>
       *
       * <pre>
       * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
       * </pre>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 userid = 3;</code>
       *
       * <pre>
       * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
       * </pre>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>optional int32 userid = 3;</code>
       *
       * <pre>
       * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
       * </pre>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000004;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userid = 3;</code>
       *
       * <pre>
       * 2014-03-06: 兼容IPv6，故只能改为用字符串传送
       * </pre>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userid_ = 0;
        onChanged();
        return this;
      }

      // required bytes logname = 4;
      private com.google.protobuf.ByteString logname_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes logname = 4;</code>
       *
       * <pre>
       * 主帐号
       * </pre>
       */
      public boolean hasLogname() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes logname = 4;</code>
       *
       * <pre>
       * 主帐号
       * </pre>
       */
      public com.google.protobuf.ByteString getLogname() {
        return logname_;
      }
      /**
       * <code>required bytes logname = 4;</code>
       *
       * <pre>
       * 主帐号
       * </pre>
       */
      public Builder setLogname(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        logname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes logname = 4;</code>
       *
       * <pre>
       * 主帐号
       * </pre>
       */
      public Builder clearLogname() {
        bitField0_ = (bitField0_ & ~0x00000008);
        logname_ = getDefaultInstance().getLogname();
        onChanged();
        return this;
      }

      // optional bytes uname = 5;
      private com.google.protobuf.ByteString uname_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uname = 5;</code>
       *
       * <pre>
       * 用户姓名
       * </pre>
       */
      public boolean hasUname() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes uname = 5;</code>
       *
       * <pre>
       * 用户姓名
       * </pre>
       */
      public com.google.protobuf.ByteString getUname() {
        return uname_;
      }
      /**
       * <code>optional bytes uname = 5;</code>
       *
       * <pre>
       * 用户姓名
       * </pre>
       */
      public Builder setUname(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uname = 5;</code>
       *
       * <pre>
       * 用户姓名
       * </pre>
       */
      public Builder clearUname() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uname_ = getDefaultInstance().getUname();
        onChanged();
        return this;
      }

      // optional int32 ouid = 6;
      private int ouid_ ;
      /**
       * <code>optional int32 ouid = 6;</code>
       *
       * <pre>
       * 组织机构ID
       * </pre>
       */
      public boolean hasOuid() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 ouid = 6;</code>
       *
       * <pre>
       * 组织机构ID
       * </pre>
       */
      public int getOuid() {
        return ouid_;
      }
      /**
       * <code>optional int32 ouid = 6;</code>
       *
       * <pre>
       * 组织机构ID
       * </pre>
       */
      public Builder setOuid(int value) {
        bitField0_ |= 0x00000020;
        ouid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ouid = 6;</code>
       *
       * <pre>
       * 组织机构ID
       * </pre>
       */
      public Builder clearOuid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ouid_ = 0;
        onChanged();
        return this;
      }

      // optional bytes ouname = 7;
      private com.google.protobuf.ByteString ouname_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ouname = 7;</code>
       *
       * <pre>
       * 组织机构名称
       * </pre>
       */
      public boolean hasOuname() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes ouname = 7;</code>
       *
       * <pre>
       * 组织机构名称
       * </pre>
       */
      public com.google.protobuf.ByteString getOuname() {
        return ouname_;
      }
      /**
       * <code>optional bytes ouname = 7;</code>
       *
       * <pre>
       * 组织机构名称
       * </pre>
       */
      public Builder setOuname(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ouname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ouname = 7;</code>
       *
       * <pre>
       * 组织机构名称
       * </pre>
       */
      public Builder clearOuname() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ouname_ = getDefaultInstance().getOuname();
        onChanged();
        return this;
      }

      // optional bytes region_code = 8;
      private com.google.protobuf.ByteString regionCode_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes region_code = 8;</code>
       *
       * <pre>
       * 主帐号地域编码
       * </pre>
       */
      public boolean hasRegionCode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes region_code = 8;</code>
       *
       * <pre>
       * 主帐号地域编码
       * </pre>
       */
      public com.google.protobuf.ByteString getRegionCode() {
        return regionCode_;
      }
      /**
       * <code>optional bytes region_code = 8;</code>
       *
       * <pre>
       * 主帐号地域编码
       * </pre>
       */
      public Builder setRegionCode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        regionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes region_code = 8;</code>
       *
       * <pre>
       * 主帐号地域编码
       * </pre>
       */
      public Builder clearRegionCode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        regionCode_ = getDefaultInstance().getRegionCode();
        onChanged();
        return this;
      }

      // optional bytes region_name = 9;
      private com.google.protobuf.ByteString regionName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes region_name = 9;</code>
       *
       * <pre>
       * 主帐号地域名称
       * </pre>
       */
      public boolean hasRegionName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes region_name = 9;</code>
       *
       * <pre>
       * 主帐号地域名称
       * </pre>
       */
      public com.google.protobuf.ByteString getRegionName() {
        return regionName_;
      }
      /**
       * <code>optional bytes region_name = 9;</code>
       *
       * <pre>
       * 主帐号地域名称
       * </pre>
       */
      public Builder setRegionName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        regionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes region_name = 9;</code>
       *
       * <pre>
       * 主帐号地域名称
       * </pre>
       */
      public Builder clearRegionName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        regionName_ = getDefaultInstance().getRegionName();
        onChanged();
        return this;
      }

      // optional int32 employeetype_id = 10;
      private int employeetypeId_ ;
      /**
       * <code>optional int32 employeetype_id = 10;</code>
       *
       * <pre>
       * 主帐号类型ID
       * </pre>
       */
      public boolean hasEmployeetypeId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 employeetype_id = 10;</code>
       *
       * <pre>
       * 主帐号类型ID
       * </pre>
       */
      public int getEmployeetypeId() {
        return employeetypeId_;
      }
      /**
       * <code>optional int32 employeetype_id = 10;</code>
       *
       * <pre>
       * 主帐号类型ID
       * </pre>
       */
      public Builder setEmployeetypeId(int value) {
        bitField0_ |= 0x00000200;
        employeetypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 employeetype_id = 10;</code>
       *
       * <pre>
       * 主帐号类型ID
       * </pre>
       */
      public Builder clearEmployeetypeId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        employeetypeId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes employeetype = 11;
      private com.google.protobuf.ByteString employeetype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes employeetype = 11;</code>
       *
       * <pre>
       * 主帐号类型名称
       * </pre>
       */
      public boolean hasEmployeetype() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional bytes employeetype = 11;</code>
       *
       * <pre>
       * 主帐号类型名称
       * </pre>
       */
      public com.google.protobuf.ByteString getEmployeetype() {
        return employeetype_;
      }
      /**
       * <code>optional bytes employeetype = 11;</code>
       *
       * <pre>
       * 主帐号类型名称
       * </pre>
       */
      public Builder setEmployeetype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        employeetype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes employeetype = 11;</code>
       *
       * <pre>
       * 主帐号类型名称
       * </pre>
       */
      public Builder clearEmployeetype() {
        bitField0_ = (bitField0_ & ~0x00000400);
        employeetype_ = getDefaultInstance().getEmployeetype();
        onChanged();
        return this;
      }

      // optional int32 employeestation_id = 12;
      private int employeestationId_ ;
      /**
       * <code>optional int32 employeestation_id = 12;</code>
       *
       * <pre>
       * 主帐号岗位ID
       * </pre>
       */
      public boolean hasEmployeestationId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 employeestation_id = 12;</code>
       *
       * <pre>
       * 主帐号岗位ID
       * </pre>
       */
      public int getEmployeestationId() {
        return employeestationId_;
      }
      /**
       * <code>optional int32 employeestation_id = 12;</code>
       *
       * <pre>
       * 主帐号岗位ID
       * </pre>
       */
      public Builder setEmployeestationId(int value) {
        bitField0_ |= 0x00000800;
        employeestationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 employeestation_id = 12;</code>
       *
       * <pre>
       * 主帐号岗位ID
       * </pre>
       */
      public Builder clearEmployeestationId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        employeestationId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes employeestation = 13;
      private com.google.protobuf.ByteString employeestation_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes employeestation = 13;</code>
       *
       * <pre>
       * 主帐号岗位名称
       * </pre>
       */
      public boolean hasEmployeestation() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bytes employeestation = 13;</code>
       *
       * <pre>
       * 主帐号岗位名称
       * </pre>
       */
      public com.google.protobuf.ByteString getEmployeestation() {
        return employeestation_;
      }
      /**
       * <code>optional bytes employeestation = 13;</code>
       *
       * <pre>
       * 主帐号岗位名称
       * </pre>
       */
      public Builder setEmployeestation(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        employeestation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes employeestation = 13;</code>
       *
       * <pre>
       * 主帐号岗位名称
       * </pre>
       */
      public Builder clearEmployeestation() {
        bitField0_ = (bitField0_ & ~0x00001000);
        employeestation_ = getDefaultInstance().getEmployeestation();
        onChanged();
        return this;
      }

      // required int64 oper_sec = 14;
      private long operSec_ ;
      /**
       * <code>required int64 oper_sec = 14;</code>
       *
       * <pre>
       * 操作时间，秒
       * </pre>
       */
      public boolean hasOperSec() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int64 oper_sec = 14;</code>
       *
       * <pre>
       * 操作时间，秒
       * </pre>
       */
      public long getOperSec() {
        return operSec_;
      }
      /**
       * <code>required int64 oper_sec = 14;</code>
       *
       * <pre>
       * 操作时间，秒
       * </pre>
       */
      public Builder setOperSec(long value) {
        bitField0_ |= 0x00002000;
        operSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 oper_sec = 14;</code>
       *
       * <pre>
       * 操作时间，秒
       * </pre>
       */
      public Builder clearOperSec() {
        bitField0_ = (bitField0_ & ~0x00002000);
        operSec_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 oper_msec = 15;
      private long operMsec_ ;
      /**
       * <code>optional int64 oper_msec = 15;</code>
       *
       * <pre>
       * 操作时间，毫秒
       * </pre>
       */
      public boolean hasOperMsec() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int64 oper_msec = 15;</code>
       *
       * <pre>
       * 操作时间，毫秒
       * </pre>
       */
      public long getOperMsec() {
        return operMsec_;
      }
      /**
       * <code>optional int64 oper_msec = 15;</code>
       *
       * <pre>
       * 操作时间，毫秒
       * </pre>
       */
      public Builder setOperMsec(long value) {
        bitField0_ |= 0x00004000;
        operMsec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 oper_msec = 15;</code>
       *
       * <pre>
       * 操作时间，毫秒
       * </pre>
       */
      public Builder clearOperMsec() {
        bitField0_ = (bitField0_ & ~0x00004000);
        operMsec_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes workinfo = 16;
      private com.google.protobuf.ByteString workinfo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes workinfo = 16;</code>
       *
       * <pre>
       * 工单信息
       * </pre>
       */
      public boolean hasWorkinfo() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional bytes workinfo = 16;</code>
       *
       * <pre>
       * 工单信息
       * </pre>
       */
      public com.google.protobuf.ByteString getWorkinfo() {
        return workinfo_;
      }
      /**
       * <code>optional bytes workinfo = 16;</code>
       *
       * <pre>
       * 工单信息
       * </pre>
       */
      public Builder setWorkinfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        workinfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes workinfo = 16;</code>
       *
       * <pre>
       * 工单信息
       * </pre>
       */
      public Builder clearWorkinfo() {
        bitField0_ = (bitField0_ & ~0x00008000);
        workinfo_ = getDefaultInstance().getWorkinfo();
        onChanged();
        return this;
      }

      // optional bytes logreason = 17;
      private com.google.protobuf.ByteString logreason_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes logreason = 17;</code>
       *
       * <pre>
       * 登录事由
       * </pre>
       */
      public boolean hasLogreason() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional bytes logreason = 17;</code>
       *
       * <pre>
       * 登录事由
       * </pre>
       */
      public com.google.protobuf.ByteString getLogreason() {
        return logreason_;
      }
      /**
       * <code>optional bytes logreason = 17;</code>
       *
       * <pre>
       * 登录事由
       * </pre>
       */
      public Builder setLogreason(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        logreason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes logreason = 17;</code>
       *
       * <pre>
       * 登录事由
       * </pre>
       */
      public Builder clearLogreason() {
        bitField0_ = (bitField0_ & ~0x00010000);
        logreason_ = getDefaultInstance().getLogreason();
        onChanged();
        return this;
      }

      // required .sp.LOG_TYPE log_type = 18;
      private AuditEnum.LOG_TYPE logType_ = AuditEnum.LOG_TYPE.LOG_UNKNOWN;
      /**
       * <code>required .sp.LOG_TYPE log_type = 18;</code>
       *
       * <pre>
       * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
       * </pre>
       */
      public boolean hasLogType() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>required .sp.LOG_TYPE log_type = 18;</code>
       *
       * <pre>
       * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
       * </pre>
       */
      public AuditEnum.LOG_TYPE getLogType() {
        return logType_;
      }
      /**
       * <code>required .sp.LOG_TYPE log_type = 18;</code>
       *
       * <pre>
       * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
       * </pre>
       */
      public Builder setLogType(AuditEnum.LOG_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00020000;
        logType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sp.LOG_TYPE log_type = 18;</code>
       *
       * <pre>
       * 审计日志类型ID，可能的值：USER_SESSION、USER_SESSION_UPDATE
       * </pre>
       */
      public Builder clearLogType() {
        bitField0_ = (bitField0_ & ~0x00020000);
        logType_ = AuditEnum.LOG_TYPE.LOG_UNKNOWN;
        onChanged();
        return this;
      }

      // optional int32 reserved0 = 19;
      private int reserved0_ ;
      /**
       * <code>optional int32 reserved0 = 19;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasReserved0() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional int32 reserved0 = 19;</code>
       *
       * <pre>
       * </pre>
       */
      public int getReserved0() {
        return reserved0_;
      }
      /**
       * <code>optional int32 reserved0 = 19;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setReserved0(int value) {
        bitField0_ |= 0x00040000;
        reserved0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reserved0 = 19;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearReserved0() {
        bitField0_ = (bitField0_ & ~0x00040000);
        reserved0_ = 0;
        onChanged();
        return this;
      }

      // optional int32 reserved1 = 20;
      private int reserved1_ ;
      /**
       * <code>optional int32 reserved1 = 20;</code>
       */
      public boolean hasReserved1() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional int32 reserved1 = 20;</code>
       */
      public int getReserved1() {
        return reserved1_;
      }
      /**
       * <code>optional int32 reserved1 = 20;</code>
       */
      public Builder setReserved1(int value) {
        bitField0_ |= 0x00080000;
        reserved1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reserved1 = 20;</code>
       */
      public Builder clearReserved1() {
        bitField0_ = (bitField0_ & ~0x00080000);
        reserved1_ = 0;
        onChanged();
        return this;
      }

      // optional bytes reserved2 = 21;
      private com.google.protobuf.ByteString reserved2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reserved2 = 21;</code>
       */
      public boolean hasReserved2() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>optional bytes reserved2 = 21;</code>
       */
      public com.google.protobuf.ByteString getReserved2() {
        return reserved2_;
      }
      /**
       * <code>optional bytes reserved2 = 21;</code>
       */
      public Builder setReserved2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00100000;
        reserved2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reserved2 = 21;</code>
       */
      public Builder clearReserved2() {
        bitField0_ = (bitField0_ & ~0x00100000);
        reserved2_ = getDefaultInstance().getReserved2();
        onChanged();
        return this;
      }

      // optional bytes reserved3 = 22;
      private com.google.protobuf.ByteString reserved3_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reserved3 = 22;</code>
       */
      public boolean hasReserved3() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <code>optional bytes reserved3 = 22;</code>
       */
      public com.google.protobuf.ByteString getReserved3() {
        return reserved3_;
      }
      /**
       * <code>optional bytes reserved3 = 22;</code>
       */
      public Builder setReserved3(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00200000;
        reserved3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reserved3 = 22;</code>
       */
      public Builder clearReserved3() {
        bitField0_ = (bitField0_ & ~0x00200000);
        reserved3_ = getDefaultInstance().getReserved3();
        onChanged();
        return this;
      }

      // optional bytes reserved4 = 23;
      private com.google.protobuf.ByteString reserved4_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reserved4 = 23;</code>
       */
      public boolean hasReserved4() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      /**
       * <code>optional bytes reserved4 = 23;</code>
       */
      public com.google.protobuf.ByteString getReserved4() {
        return reserved4_;
      }
      /**
       * <code>optional bytes reserved4 = 23;</code>
       */
      public Builder setReserved4(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00400000;
        reserved4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reserved4 = 23;</code>
       */
      public Builder clearReserved4() {
        bitField0_ = (bitField0_ & ~0x00400000);
        reserved4_ = getDefaultInstance().getReserved4();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sp.T_USER_SESSION)
    }

    static {
      defaultInstance = new T_USER_SESSION(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sp.T_USER_SESSION)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sp_T_USER_SESSION_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sp_T_USER_SESSION_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021audit_usess.proto\022\002sp\032\020audit_enum.prot" +
      "o\"\325\003\n\016T_USER_SESSION\022\021\n\tsessionid\030\001 \002(\014\022" +
      "\013\n\003sip\030\002 \002(\014\022\016\n\006userid\030\003 \001(\005\022\017\n\007logname\030" +
      "\004 \002(\014\022\r\n\005uname\030\005 \001(\014\022\014\n\004ouid\030\006 \001(\005\022\016\n\006ou" +
      "name\030\007 \001(\014\022\023\n\013region_code\030\010 \001(\014\022\023\n\013regio" +
      "n_name\030\t \001(\014\022\027\n\017employeetype_id\030\n \001(\005\022\024\n" +
      "\014employeetype\030\013 \001(\014\022\032\n\022employeestation_i" +
      "d\030\014 \001(\005\022\027\n\017employeestation\030\r \001(\014\022\020\n\010oper" +
      "_sec\030\016 \002(\003\022\021\n\toper_msec\030\017 \001(\003\022\020\n\010workinf" +
      "o\030\020 \001(\014\022\021\n\tlogreason\030\021 \001(\014\022\036\n\010log_type\030\022",
      " \002(\0162\014.sp.LOG_TYPE\022\021\n\treserved0\030\023 \001(\005\022\021\n" +
      "\treserved1\030\024 \001(\005\022\021\n\treserved2\030\025 \001(\014\022\021\n\tr" +
      "eserved3\030\026 \001(\014\022\021\n\treserved4\030\027 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sp_T_USER_SESSION_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sp_T_USER_SESSION_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sp_T_USER_SESSION_descriptor,
              new String[] { "Sessionid", "Sip", "Userid", "Logname", "Uname", "Ouid", "Ouname", "RegionCode", "RegionName", "EmployeetypeId", "Employeetype", "EmployeestationId", "Employeestation", "OperSec", "OperMsec", "Workinfo", "Logreason", "LogType", "Reserved0", "Reserved1", "Reserved2", "Reserved3", "Reserved4", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AuditEnum.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
